project:
  group: loafer
  name: springboot

service:
  port: 8887
  context-path: /loafer

database:
  ip:
  port: 3306
  name: base
  username:
  password: 

druid:
  url-pattern: /druid/*
  username: loafer
  password: loafer

token:
  expire: 3600

redis:
  host: localhost
  port: 6379
  password: