project:
  group: loafer
  name: springboot

service:
  port: 8888
  context-path: /loafer

database:
  ip: 49.234.210.243
  port: 3306
  name: base
  username: root
  password: ll5271211314

druid:
  url-pattern: /druid/*
  username: loafer
  password: loafer

token:
  expire: 3600

redis:
  host: localhost
  port: 6379
  password: