project:
  group: loafer
  name: springboot

service:
  port: 8888
  context-path: /loafer

database:
  ip: 192.168.1.157
  port: 30306
  name: basevue3
  username: root
  password: 123456

druid:
  url-pattern: /druid/*
  username: loafer
  password: loafer

token:
  expire: 3600

redis:
  host: 192.168.1.157
  port: 30379
  password: 123456